<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines contain the default error messages used by
    | the validator class. Some of these rules have multiple versions such
    | such as the size rules. Feel free to tweak each of these messages.
    |
    */

    "accepted"             => "Le champ :attribute doit être accepté.",
    "active_url"           => "Le champ :attribute n'est pas une URL valide.",
    "after"                => "Le champ :attribute doit être une date postérieure au :date.",
    'after_or_equal'       => "Le champ :attribute doit être une date après ou égale à :date.",
    "alpha"                => "Le champ :attribute doit seulement contenir des lettres.",
    "alpha_dash"           => "Le champ :attribute doit seulement contenir des lettres, des chiffres et des tirets.",
    "alpha_num"            => "Le champ :attribute doit seulement contenir des chiffres et des lettres.",
    "array"                => "Le champ :attribute doit être un tableau.",
    "before"               => "Le champ :attribute doit être une date antérieure au :date.",
    'before_or_equal'      => 'Le champ :attribute: doit être une date avant ou égale à :date.',
    "between"              => [
        "numeric" => "La valeur de :attribute doit être comprise entre :min et :max.",
        "file"    => "Le fichier :attribute doit avoir une taille entre :min et :max kilo-octets.",
        "string"  => "Le texte :attribute doit avoir entre :min et :max caractères.",
        "array"   => "Le tableau :attribute doit avoir entre :min et :max éléments.",
    ],
    "boolean"              => "Le champ :attribute doit être vrai ou faux.",
    "confirmed"            => "Le champ de confirmation :attribute ne correspond pas.",
    "date"                 => "Le champ :attribute n'est pas une date valide.",
    'date_equals'          => 'Le champ :attribute doit être une date égale à :date.',
    "date_format"          => "Le champ :attribute ne correspond pas au format :format.",
    "different"            => "Les champs :attribute et :other doivent être différents.",
    "digits"               => "Le champ :attribute doit avoir :digits chiffres.",
    "digits_between"       => "Le champ :attribute doit avoir entre :min and :max chiffres.",
    'dimensions'           => "Le champ :attribute a des dimensions d'image non valides.",
    'distinct'             => 'Le champ a une valeur en double.',
    "email"                => "Le champ :attribute doit être une adresse email valide.",
    'ends_with' => 'The :attribute must end with one of the following: :values',
    "exists"               => "Le champ :attribute sélectionné est invalide.",
    'file'                 => 'Le champ :attribute doit être un fichier.',
    "filled"               => "Le champ :attribute est obligatoire.",
    'gt' => [
        'numeric' => 'Le champ :attribute doit être supérieur à :value.',
        'file' => 'Le champ :attribute doit être supérieur à :value kilobytes.',
        'string' => 'Le champ :attribute doit être supérieur à :value caractères.',
        'array' => 'Le champ :attribute doit avoir plus de :value éléments.',
    ],
    'gte' => [
        'numeric' => 'Le champ :attribute doit être supérieur ou égal :value.',
        'file' => 'Le champ :attribute doit être supérieur ou égal :value kilobytes.',
        'string' => 'Le champ :attribute doit être supérieur ou égal :value caractères.',
        'array' => 'Le champ :attribute doit avoir :value éléments ou plus.',
    ],
    "image"                => "Le champ :attribute doit être une image.",
    "in"                   => "Le champ :attribute est invalide.",
    'in_array'             => "Le champ :attribute n'existe pas dans :other.",
    "integer"              => "Le champ :attribute doit être un entier (un nombre sans virgule).",
    "ip"                   => "Le champ :attribute doit être une adresse IP valide.",
    'ipv4'                 => 'Le champ :attribute doit être une adresse IPv4 valide.',
    'ipv6'                 => 'Le champ :attribute doit être une adresse IPv6 valide.',
    'json'                 => 'Le champ :attribute doit être une chaîne JSON valide.',
    'lt' => [
        'numeric' => 'Le champ :attribute doit être inférieur à :value.',
        'file' => 'Le champ :attribute doit être inférieur à :value kilobytes.',
        'string' => 'Le champ :attribute doit être inférieur à :value caractères.',
        'array' => 'Le champ :attribute doit avoir moins de :value éléments.',
    ],
    'lte' => [
        'numeric' => 'Le champ :attribute doit être inférieur à or equal :value.',
        'file' => 'Le champ :attribute doit être inférieur à or equal :value kilobytes.',
        'string' => 'Le champ :attribute doit être inférieur à or equal :value caractères.',
        'array' => 'Le champ :attribute ne doit pas avoir plus de :value éléments.',
    ],
    "max"                  => [
        "numeric" => "La valeur de :attribute ne peut être supérieure à :max.",
        "file"    => "Le fichier :attribute ne peut être plus gros que :max kilo-octets.",
        "string"  => "Le texte de :attribute ne peut contenir plus de :max caractères.",
        "array"   => "Le tableau :attribute ne peut avoir plus de :max éléments.",
    ],
    "mimes"                => "Le champ :attribute doit être un fichier de type : :values.",
    'mimetypes'            => 'Le champ :attribute doit être un fichier de type : :values.',
    "min"                  => [
        "numeric" => "La valeur de :attribute doit être au moins de :min.",
        "file"    => "Le fichier :attribute doit être au moins de :min kilo-octets.",
        "string"  => "Le texte du champ :attribute doit contenir au moins :min caractères.",
        "array"   => "Le tableau :attribute doit avoir au moins :min éléments.",
    ],
    "not_in"               => "Le champ :attribute sélectionné n'est pas valide.",
    'not_regex' => 'Le champ :attribute a un format invalide.',
    "numeric"              => "Le champ :attribute doit contenir un nombre.",
    'password' => 'The password is incorrect.',
    'present'              => 'Le champ :attribute doit être present.',
    "regex"                => "Le format du champ :attribute est invalide.",
    "required"             => "Le champ :attribute est obligatoire.",
    "required_if"          => "Le champ :attribute est obligatoire quand la valeur de :other est :value.",
    'required_unless'      => 'Le champ :attribute est obligatoire sauf si :other est dans :values.',
    "required_with"        => "Le champ :attribute est obligatoire quand :values est présent.",
    "required_with_all"    => "Le champ :attribute est obligatoire quand :values est présent.",
    "required_without"     => "Le champ :attribute est obligatoire quand :values n'est pas présent.",
    "required_without_all" => "Le champ :attribute est requis quand aucun de :values n'est présent.",
    "same"                 => "Les champs :attribute et :other doivent être identiques.",
    "size"                 => [
        "numeric" => "La valeur de :attribute doit être :size.",
        "file"    => "La taille du fichier de :attribute doit être de :size kilo-octets.",
        "string"  => "Le texte de :attribute doit contenir :size caractères.",
        "array"   => "Le tableau :attribute doit contenir :size éléments.",
    ],
    'starts_with'          => "Le champ :attribute doit commencer par l'un des éléments suivants : :values",
    "string"               => "Le champ :attribute doit être une chaîne de caractères.",
    "timezone"             => "Le champ :attribute doit être un fuseau horaire valide.",
    "unique"               => "La valeur du champ :attribute est déjà utilisée.",
    'uploaded'             => 'Le champ :attribute a échoué à télécharger.',
    "url"                  => "Le format de l'URL de :attribute n'est pas valide.",
    'uuid'                 => 'Le champ :attribute doit être un UUID valide.',

    /*
    |--------------------------------------------------------------------------
    | Custom Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | Here you may specify custom validation messages for attributes using the
    | convention "attribute.rule" to name the lines. This makes it quick to
    | specify a specific custom language line for a given attribute rule.
    |
    */

    'custom' => [
        'attribute-name' => [
            'rule-name' => 'custom-message',
        ],
        'city_code' => [
            'in' => 'Veuillez choisir une ville valide.',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Custom Validation Attributes
    |--------------------------------------------------------------------------
    |
    | The following language lines are used to swap attribute place-holders
    | with something more reader friendly such as E-Mail Address instead
    | of "email". This simply helps us make messages a little cleaner.
    |
    */

    'attributes' => [
        "activity" => "activité",
        "activity_detail" => "détail de l'activité",
        "activity_details" => "détails de l'activité",
        "activities" => "activités",
        "activities_detail" => "détail des activités",
        "activities_details" => "détails des activités",
        "address" => "adresse",
        "addresses" => "adresses",
        "address_street" => "n° + libellé de la voie",
        "address_postal_code" => "code postal",
        "address_city" => "ville",
        "address_complement" => "complément d'adresse",
        "address_department" => "département",
        "address_region" => "région",
        "address_country" => "pays",
        "age" => "âge",
        "ages" => "âges",
        "amount" => "montant",
        "amounts" => "montants",
        "answer" => "réponse",
        "answers" => "réponses",
        "answers.*" => "d'une des réponses",
        "authorize_comments" => "autoriser ou non les commentaires",
        "available" => "disponible",
        "availables" => "disponibles",
        "barcode" => "code-barres",
        "barcodes" => "codes-barres",
        "birth_date" => "date de naissance",
        "birth_date_day" => "jour de la date de naissance",
        "birth_date_month" => "mois de la date de naissance",
        "birth_date_year" => "année de la date de naissance",
        "brand" => "marque",
        "brands" => "marques",
        "brand_name" => "nom de la marque",
        "buying_price" => "prix d'achat",
        "buying_price_ht" => "prix d'achat HT",
        "buying_price_ttc" => "prix d'achat TTC",
        "business_name" => "nom de votre entreprise",
        "category" => "categorie",
        "categories" => "catégories",
        "categories.*" => "d'une des catégories",
        "cb_code" => "code de la CB",
        "cb_mm" => "mois d'Expiration de la CB",
        "cb_yy" => "année d'Expiration de la CB",
        "cb_cvv" => "code de Validation de la CB",
        "cb_cvc" => "code de Validation de la CB",
        "city" => "ville",
        "cities" => "villes",
        "city_code" => "code de la ville",
        "civility" => "civilité",
        "civilities" => "civilités",
        "close_start" => "fermé de",
        "close_end" => "fermé jusqu'à",
        "close_new_comments" => "fermer les nouveaux commentaires",
        "comment" => "commentaire",
        "comments" => "commentaires",
        "company" => "entreprise",
        "companies" => "entreprises",
        "company_name" => "nom de votre entreprise",
        "company_siret" => "SIRET de votre entreprise",
        "confirmed" => "confirmé",
        "confirmed_at" => "confirmé le",
        "content" => "contenu",
        "contents" => "contenus",
        "country" => "pays",
        "countries" => "pays",
        "customer_email" => "email du client",
        "customer_first_name" => "prénom du client",
        "customer_id" => "identifiant client",
        "customer_last_name" => "nom du client",
        "customer_tel" => "téléphone du client",
        "customer_question" => "question client",
        "customer_questions" => "questions client",
        "day" => "jour",
        "days" => "jours",
        "date_close_end" => "fermé jusqu'à",
        "date_close_start" => "fermé de",
        "date_end" => "date de fin",
        "date_for_month" => "date pour le mois",
        "date_for_month_year" => "date pour le mois/année",
        "date_start" => "date de début",
        "delivery_address_city" => "ville (pour livraison)",
        "delivery_address_complement" => "complément d'adresse (pour livraison)",
        "delivery_address_postal_code" => "code postal (pour livraison)",
        'delivery_address_street' => 'n° + libellé de la voie (pour livraison)',
        "delivery_date" => "date de livraison",
        "directory" => "dossier",
        "directory_name" => "nom du dossier",
        "directories" => "dossiers",
        "directories_name" => "nom des dossiers",
        "directories_names" => "noms des dossiers",
        "doc_kbis" => "document kbis",
        "doc_id" => "document pièce d'identité",
        "doc_student_card" => "document carte étudiante",
        "doc_type" => "type du document",
        "eco_participation" => "eco participation",
        "eco_participation_ht" => "eco participation HT",
        "eco_participation_ttc" => "eco participation TTC",
        "excerpt" => "extrait",
        "excerpts" => "extraits",
        "email_banned" => "email banni",
        "email_confirmed" => "email confirmé",
        "email_validated" => "email validé",
        "email_prohibited" => "email inerdit",
        "emails_banned" => "emails bannis",
        "emails_confirmed" => "emails confirmés",
        "emails_validated" => "emails validés",
        "emails_prohibited" => "emails inerdits",
        "file" => "fichier",
        "files" => "fichiers",
        "file_for_store" => "fichier pour ajouter",
        "file_for_update" => "fichier pour modifier",
        "file_image" => "fichier image",
        "file_joined" => "fichier joint",
        "file_logo" => "fichier logo",
        "file_new" => "nouveau fichier",
        "first_name" => "prénom",
        "first_names" => "prénoms",
        "full_address" => "adresse complète",
        "full_addresss" => "adresses complètes",
        "gender" => "genre",
        "genders" => "genres",
        "h1" => "titre H1",
        "h2" => "titre H2",
        "h3" => "titre H3",
        "h4" => "titre H4",
        "h5" => "titre H5",
        "h6" => "titre H6",
        "hour" => "heure",
        "hour_end" => "heure de fin",
        "hour_end.*" => "l'une des heures de fin",
        "hour_end_am" => '"Ouvert le matin jusqu\'à"',
        "hour_end_am.*" => 'l\'une des heures de "Ouvert le matin jusqu\'à"',
        "hour_end_pm" => '"Ouvert l\'après-midi jusqu\'à"',
        "hour_end_pm.*" => 'l\'une des heures de "Ouvert l\'après-midi jusqu\'à"',
        "hour_start" => "heure de début",
        "hour_start.*" => "l'une des heures de début",
        "hour_start_am" => '"Ouvert le matin de"',
        "hour_start_am.*" => 'l\'une des heures de "Ouvert le matin de"',
        "hour_start_pm" => '"Ouvert l\'après-midi de"',
        "hour_start_pm.*" => 'l\'une des heures de "Ouvert l\'après-midi de"',
        "hours" => "heures",
        "hours.*" => "l'une des heures",
        "is_active" => "est actif ?",
        "is_banned" => "bannir ?",
        "job" => "métier",
        "jobs" => "métiers",
        "last_name" => "nom",
        "last_names" => "noms",
        "link" => "lien",
        "links" => "liens",
        "mobile" => "téléphone portable",
        "mobiles" => "téléphones portable",
        "month" => "mois",
        "name" => "nom",
        "namse" => "noms",
        "nb_hours" => "nombre d'heures",
        "newsletter_email" => "email de newsletter",
        "number_in_stock" => "nombre en stock",
        "office" => "bureau",
        "offices" => "bureaux",
        "offices.*" => "d'un des bureaux",
        "office_type" => "type de bureau",
        "other" => "autre",
        "others" => "autres",
        "password" => "mot de passe",
        "password_confirmation" => "confirmation du mot de passe",
        "password_current" => "mot de passe actuel",
        "passwords" => "mots de passe",
        "percentage_reduction" => "réduction en pourcentage",
        "percentage_reduction_category" => "réduction en pourcentage pour la catégorie",
        "phone" => "téléphone",
        "phones" => "téléphones",
        "price" => "prix",
        "price_delivery" => "prix de livraison",
        "price_furniture" => "prix du mobilier",
        "price_pose" => "prix de la pose",
        "price_ht" => "prix HT",
        "price_ht_delivery" => "prix HT de livraison",
        "price_ht_furniture" => "prix HT du mobilier",
        "price_ht_pose" => "prix HT de la pose",
        "price_ttc" => "prix TTC",
        "price_ttc_delivery" => "prix TTC de livraison",
        "price_ttc_furniture" => "prix TTC du mobilier",
        "price_ttc_pose" => "prix TTC de la pose",
        "product_category" => "catégorie de produit",
        "product_categories" => "catégories de produit",
        "products_category" => "catégorie des produits",
        "products_categories" => "catégories des produits",
        "published_at" => "date de publication",
        "quantity" => "quantité",
        "quantity_in_stock" => "quantité en stock",
        "quantity_to_order" => "quantité à commander",
        "quantity_to_order.*" => "d'une des quantités à commander",
        "quantity_to_order_sav" => "quantité à commander (SAV)",
        "quantity_to_remove_to_reserve_stock" => "quantité à enlever au stock de réserve",
        "quantity_to_remove_to_reserve_stock_sav" => "quantité à enlever au stock de réserve (SAV)",
        "quantity_to_remove_to_stock" => "quantité à enlever au stock",
        "quantity_to_remove_to_stock_sav" => "quantité à enlever au stock (SAV)",
        "quantities" => "quantités",
        "quantities_in_stock" => "quantités en stock",
        "quantities_to_order" => "quantités à commander",
        "quantities_to_order.*" => "d'une des quantités à commander",
        "quantities_to_order_sav" => "quantités à commander (SAV)",
        "quantities_to_order_sav.*" => "d'une des quantités à commander (SAV)",
        "quantities_to_remove_to_reserve_stock" => "quantités à enlever au stock de réserve",
        "quantities_to_remove_to_reserve_stock.*" => "d'une des quantités à enlever au stock de réserve",
        "quantities_to_remove_to_reserve_stock_sav" => "quantités à enlever au stock de réserve (SAV)",
        "quantities_to_remove_to_reserve_stock_sav.*" => "d'une des quantités à enlever au stock de réserve (SAV)",
        "quantities_to_remove_to_stock" => "quantités à enlever au stock",
        "quantities_to_remove_to_stock.*" => "d'une des quantités à enlever au stock",
        "quantities_to_remove_to_stock_sav" => "quantités à enlever au stock (SAV)",
        "quantities_to_remove_to_stock_sav.*" => "d'une des quantités à enlever au stock (SAV)",
        "rate" => "taux",
        "rates" => "taux",
        "real_stock" => "stock réel",
        "reals_stock" => "stocks réel",
        "reception_desired_for_the" => "réception souhaité pour le",
        "reception_planned_at" => "réception prévue le",
        "reference" => "référence",
        "references" => "références",
        "response" => "réponse",
        "responses" => "réponses",
        "role" => "rôle",
        "roles" => "rôles",
        "second" => "seconde",
        "seconds" => "secondes",
        "sex" => "sexe",
        "shop" => "magasin",
        "shops" => "magasins",
        "shops.*" => "d'un des magasins",
        "shop_active" => "magasin actif",
        "short_title" => "titre court",
        "short_titles" => "titres courts",
        "siren" => "numéro de siren",
        "siret" => "numéro de siret",
        "size" => "taille",
        "sizes" => "tailles",
        "status" => "statut",
        "statutes" => "statuts",
        "subfolder" => "sous-dossier",
        "subfolders" => "sous-dossiers",
        "subdirectory" => "sous-dossier",
        "subdirectory_where_create_directory" => "dans quel sous-dossier créer ce dossier",
        "subdirectory_where_upload" => "dans quel sous-dossier uploader le(s) fichier(s)",
        "subdirectories" => "sous-dossiers",
        "subdirectories_where_upload" => "dans quels sous-dossiers uploader",
        "subject" => "sujet",
        "subjects" => "sujets",
        "summary" => "chapô",
        "summarys" => "chapôs",
        "supplier" => "fournisseur",
        "supplier_id" => "fournisseur",
        "supplier_to_order" => "fournisseur à commander",
        "suppliers" => "fournisseurs",
        "suppliers.*" => "d'un des fournisseurs",
        "suppliers_to_order" => "fournisseurs à commander",
        "suppliers_to_order.*" => "d'un des fournisseurs à commander",
        "tax" => "taxe",
        "taxes" => "taxes",
        "tel" => "téléphone",
        "tels" => "téléphones",
        "time" => "heure",
        "title" => "titre",
        "titles" => "titres",
        "to_ordered_the" => "à commander pour le",
        "user" => "utilisateur",
        "users" => "utilisateurs",
        "users.*" => "d'un des utilisateurs",
        "username" => "pseudo",
        "usernames" => "pseudos",
        "value" => "valeur",
        "values" => "valeurs",
        "vat" => "TVA",
        "website" => "site web",
        "websites" => "sites web",
        "year" => "année",
        "years" => "années",
    ],

];
