<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines contain the default error messages used by
    | the validator class. Some of these rules have multiple versions such
    | such as the size rules. Feel free to tweak each of these messages.
    |
    */

    "accepted"             => "Le champ :attribute doit être accepté.",
    "active_url"           => "Le champ :attribute n'est pas une URL valide.",
    "after"                => "Le champ :attribute doit être une date postérieure au :date.",
    'after_or_equal'       => "Le champ :attribute doit être une date après ou égale à :date.",
    "alpha"                => "Le champ :attribute doit seulement contenir des lettres.",
    "alpha_dash"           => "Le champ :attribute doit seulement contenir des lettres, des chiffres et des tirets.",
    "alpha_num"            => "Le champ :attribute doit seulement contenir des chiffres et des lettres.",
    "array"                => "Le champ :attribute doit être un tableau.",
    "before"               => "Le champ :attribute doit être une date antérieure au :date.",
    'before_or_equal'      => 'Le champ :attribute: doit être une date avant ou égale à :date.',
    "between"              => [
        "numeric" => "La valeur de :attribute doit être comprise entre :min et :max.",
        "file"    => "Le fichier :attribute doit avoir une taille entre :min et :max kilo-octets.",
        "string"  => "Le texte :attribute doit avoir entre :min et :max caractères.",
        "array"   => "Le tableau :attribute doit avoir entre :min et :max éléments.",
    ],
    "boolean"              => "Le champ :attribute doit être vrai ou faux.",
    "confirmed"            => "Le champ de confirmation :attribute ne correspond pas.",
    "date"                 => "Le champ :attribute n'est pas une date valide.",
    'date_equals'          => 'Le champ :attribute doit être une date égale à :date.',
    "date_format"          => "Le champ :attribute ne correspond pas au format :format.",
    "different"            => "Les champs :attribute et :other doivent être différents.",
    "digits"               => "Le champ :attribute doit avoir :digits chiffres.",
    "digits_between"       => "Le champ :attribute doit avoir entre :min and :max chiffres.",
    'dimensions'           => "Le champ :attribute a des dimensions d'image non valides.",
    'distinct'             => 'Le champ a une valeur en double.',
    "email"                => "Le champ :attribute doit être une adresse email valide.",
    'ends_with' => 'The :attribute must end with one of the following: :values',
    "exists"               => "Le champ :attribute sélectionné est invalide.",
    'file'                 => 'Le champ :attribute doit être un fichier.',
    "filled"               => "Le champ :attribute est obligatoire.",
    'gt' => [
        'numeric' => 'Le champ :attribute doit être supérieur à :value.',
        'file' => 'Le champ :attribute doit être supérieur à :value kilobytes.',
        'string' => 'Le champ :attribute doit être supérieur à :value caractères.',
        'array' => 'Le champ :attribute doit avoir plus de :value éléments.',
    ],
    'gte' => [
        'numeric' => 'Le champ :attribute doit être supérieur ou égal :value.',
        'file' => 'Le champ :attribute doit être supérieur ou égal :value kilobytes.',
        'string' => 'Le champ :attribute doit être supérieur ou égal :value caractères.',
        'array' => 'Le champ :attribute doit avoir :value éléments ou plus.',
    ],
    "image"                => "Le champ :attribute doit être une image.",
    "in"                   => "Le champ :attribute est invalide.",
    'in_array'             => "Le champ :attribute n'existe pas dans :other.",
    "integer"              => "Le champ :attribute doit être un entier.",
    "ip"                   => "Le champ :attribute doit être une adresse IP valide.",
    'ipv4'                 => 'Le champ :attribute doit être une adresse IPv4 valide.',
    'ipv6'                 => 'Le champ :attribute doit être une adresse IPv6 valide.',
    'json'                 => 'Le champ :attribute doit être une chaîne JSON valide.',
    'lt' => [
        'numeric' => 'Le champ :attribute doit être inférieur à :value.',
        'file' => 'Le champ :attribute doit être inférieur à :value kilobytes.',
        'string' => 'Le champ :attribute doit être inférieur à :value caractères.',
        'array' => 'Le champ :attribute doit avoir moins de :value éléments.',
    ],
    'lte' => [
        'numeric' => 'Le champ :attribute doit être inférieur à or equal :value.',
        'file' => 'Le champ :attribute doit être inférieur à or equal :value kilobytes.',
        'string' => 'Le champ :attribute doit être inférieur à or equal :value caractères.',
        'array' => 'Le champ :attribute ne doit pas avoir plus de :value éléments.',
    ],
    "max"                  => [
        "numeric" => "La valeur de :attribute ne peut être supérieure à :max.",
        "file"    => "Le fichier :attribute ne peut être plus gros que :max kilo-octets.",
        "string"  => "Le texte de :attribute ne peut contenir plus de :max caractères.",
        "array"   => "Le tableau :attribute ne peut avoir plus de :max éléments.",
    ],
    "mimes"                => "Le champ :attribute doit être un fichier de type : :values.",
    'mimetypes'            => 'Le champ :attribute doit être un fichier de type : :values.',
    "min"                  => [
        "numeric" => "La valeur de :attribute doit être supérieure à :min.",
        "file"    => "Le fichier :attribute doit être plus gros que :min kilo-octets.",
        "string"  => "Le texte du champ :attribute doit contenir au moins :min caractères.",
        "array"   => "Le tableau :attribute doit avoir au moins :min éléments.",
    ],
    "not_in"               => "Le champ :attribute sélectionné n'est pas valide.",
    'not_regex' => 'Le champ :attribute a un format invalide.',
    "numeric"              => "Le champ :attribute doit contenir un nombre.",
    'present'              => 'Le champ :attribute doit être present.',
    "regex"                => "Le format du champ :attribute est invalide.",
    "required"             => "Le champ :attribute est obligatoire.",
    "required_if"          => "Le champ :attribute est obligatoire quand la valeur de :other est :value.",
    'required_unless'      => 'Le champ :attribute est obligatoire sauf si :other est dans :values.',
    "required_with"        => "Le champ :attribute est obligatoire quand :values est présent.",
    "required_with_all"    => "Le champ :attribute est obligatoire quand :values est présent.",
    "required_without"     => "Le champ :attribute est obligatoire quand :values n'est pas présent.",
    "required_without_all" => "Le champ :attribute est requis quand aucun de :values n'est présent.",
    "same"                 => "Les champs :attribute et :other doivent être identiques.",
    "size"                 => [
        "numeric" => "La valeur de :attribute doit être :size.",
        "file"    => "La taille du fichier de :attribute doit être de :size kilo-octets.",
        "string"  => "Le texte de :attribute doit contenir :size caractères.",
        "array"   => "Le tableau :attribute doit contenir :size éléments.",
    ],
    'starts_with'          => "Le champ :attribute doit commencer par l'un des éléments suivants : :values",
    "string"               => "Le champ :attribute doit être une chaîne de caractères.",
    "timezone"             => "Le champ :attribute doit être un fuseau horaire valide.",
    "unique"               => "La valeur du champ :attribute est déjà utilisée.",
    'uploaded'             => 'Le champ :attribute a échoué à télécharger.',
    "url"                  => "Le format de l'URL de :attribute n'est pas valide.",
    'uuid'                 => 'Le champ :attribute doit être un UUID valide.',

    /*
    |--------------------------------------------------------------------------
    | Custom Validation Language Lines
    |--------------------------------------------------------------------------
    |
    | Here you may specify custom validation messages for attributes using the
    | convention "attribute.rule" to name the lines. This makes it quick to
    | specify a specific custom language line for a given attribute rule.
    |
    */

    'custom' => [
        'attribute-name' => [
            'rule-name' => 'custom-message',
        ],
        'city_code' => [
            'in' => 'Veuillez choisir une ville valide.',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Custom Validation Attributes
    |--------------------------------------------------------------------------
    |
    | The following language lines are used to swap attribute place-holders
    | with something more reader friendly such as E-Mail Address instead
    | of "email". This simply helps us make messages a little cleaner.
    |
    */

    'attributes' => [
        "activity" => "activité",
        "activity_id" => "activité",
        "activities" => "activités",
        "activities_id" => "activités",
        "address" => "adresse",
        "address_street" => "n° + libellé de la voie",
        "address_postal_code" => "code postal",
        "address_city" => "ville",
        "address_complement" => "complément d'adresse",
        "address_department" => "département",
        "address_region" => "région",
        "address_country" => "pays",
        "age" => "age",
        "answer" => "réponse",
        "answers" => "réponses",
        "authorize_comments" => "autoriser ou non les commentaires",
        "available" => "disponible",
        "barcode" => "code-barres",
        "birth_date" => "date de naissance",
        "brand" => "marque",
        "brand_id" => "marque",
        "brand_name" => "nom de la marque",
        "buying_price_ht" => "prix d'achat HT",
        "business_name" => "nom de votre entreprise",
        "categories_id" => "catégories",
        "categories_id.*" => "d'une des catégories",
        "category" => "categorie",
        "cb_code" => "Code de la CB",
        "cb_mm" => "Mois d'Expiration de la CB",
        "cb_yy" => "Année d'Expiration de la CB",
        "cb_cvv" => "Code de Validation de la CB",
        "cb_cvc" => "Code de Validation de la CB",
        "checkbox_products_id" => "case à cocher des produits",
        "checkbox_products_id_sav" => "case à cocher des produits (SAV)",
        "city" => "ville",
        "city_code" => "ville",
        "civility" => "civilité",
        "close_start" => "fermé de",
        "close_end" => "fermé jusqu'à",
        "close_new_comments" => "fermer les nouveaux commentaires",
        "comment" => "commentaire",
        "company_name" => "nom de votre entreprise",
        "company_siret" => "SIRET de votre entreprise",
        "confirmed" => "confirmé",
        "content" => "contenu",
        "country" => "pays",
        "customer_email" => "email du client",
        "customer_first_name" => "prénom du client",
        "customer_id" => "identifiant client",
        "customer_last_name" => "nom du client",
        "customer_tel" => "téléphone du client",
        "customer_question" => "question client",
        "customer_questions" => "questions client",
        "customer_questions.*" => "d'une des questions client",
        "customer_row_reference" => "identifiant client N°",
        "day" => "jour",
        "date_end" => "date de fin",
        "date_start" => "date de début",
        "delivery_address_city" => "ville (pour livraison)",
        "deliveryaddress_complement" => "complément d'adresse (pour livraison)",
        "delivery_address_postal_code" => "code postal (pour livraison)",
        'delivery_address_street' => 'n° + libellé de la voie (pour livraison)',
        "delivery_date" => "date de livraison",
        "directory" => "dossier",
        "directory_name" => "nom du dossier",
        "eco_participation_ht" => "eco participation HT",
        "eco_participation_ttc" => "eco participation TTC",
        "excerpt" => "extrait",
        "email_confirmation" => "confirmation de l'Email",
        "emails_prohibited" => "emails bannis",
        "emails_confirmed" => "emails validés",
        "file" => "fichier",
        "file_for_update" => "fichier pour modifier",
        "file_image" => "image",
        "file_joined" => "fichier joint",
        "file_logo" => "logo",
        "first_name" => "prénom",
        "full_address" => "adresse complète",
        "file_avatar" => "avatar",
        "filter_services_by_job" => "filtrer les services par ce métier",
        "gender" => "genre",
        "h1" => "titre H1",
        "hour" => "heure",
        "hour.*" => "l'une des heures",
        "hour_end" => "heure de fin",
        "hour_end.*" => "l'une des heures de fin",
        "hour_end_am" => '"Ouvert le matin jusqu\'à"',
        "hour_end_am.*" => 'l\'une des heures de "Ouvert le matin jusqu\'à"',
        "hour_end_pm" => '"Ouvert l\'après-midi jusqu\'à"',
        "hour_end_pm.*" => 'l\'une des heures de "Ouvert l\'après-midi jusqu\'à"',
        "hour_start" => "heure de début",
        "hour_start.*" => "l'une des heures de début",
        "hour_start_am" => '"Ouvert le matin de"',
        "hour_start_am.*" => 'l\'une des heures de "Ouvert le matin de"',
        "hour_start_pm" => '"Ouvert l\'après-midi de"',
        "hour_start_pm.*" => 'l\'une des heures de "Ouvert l\'après-midi de"',
        "is_active" => "est actif ?",
        "job" => "métier",
        "jobs" => "métiers",
        "job_service" => "prestation",
        "job_services" => "prestations",
        "job_service_generic_question" => "question générique",
        "job_service_generic_question_answer" => "réponse",
        "job_service_question" => "question",
        "job_service_questions" => "questions",
        "job_service_question_answer" => "réponse",
        "job_service_question_answers" => "réponses",
        "last_name" => "nom",
        "link" => "lien",
        "minute" => "minute",
        "mobile" => "téléphone Portable",
        "month" => "mois",
        "name" => "nom",
        "newsletter_email" => "email",
        "number_in_stock" => "nombre en stock",
        "offer_installation" => "offre installation",
        "order_payments_to_pay.*" => "d'un des acomptes",
        "other" => "autre",
        "order_basket_product_reduction_comments.*" => "commentaire de l'une des reductions de produit",
        "order_basket_product_reduction_prices.*" => "prix de l'une des reductions de produit",
        "others" => "autres",
        "password" => "mot de passe",
        "password_confirmation" => "confirmation du mot de passe",
        "password_current" => "mot de passe actuel",
        "percentage_reduction" => "réduction en pourcentage",
        "percentage_reduction_category" => "réduction en pourcentage pour la catégorie",
        "phone" => "téléphone",
        "price" => "prix",
        "price_ht" => "prix HT",
        "price_ttc" => "prix TTC",
        "price_ttc_delivery" => "prix TTC de livraison",
        "price_ttc_furniture" => "prix TTC du mobilier",
        "price_ttc_pose" => "prix TTC de la pose",
        "product_categories_percentage_reduction" => "réduction en pourcentage pour la catégorie",
        "product_categories_percentage_reduction.*" => "réduction en pourcentage pour une des catégories",
        "product_category_id" => "catégorie de produit",
        "products_controlled_at_id" => "produit controlé le",
        "products_controlled_at_id.*" => "d'un des produits controlé le",
        "products_ordered_installed_at_id" => "produits commandés posés",
        "products_ordered_installed_at_id.*" => "d'un des produits commandés posés",
        "products_removed_to_stock_installed_at_id" => "produits enlevés au stock posés",
        "products_removed_to_stock_installed_at_id.*" => "d'un des produits enlevés au stock posés",
        "published_at" => "date de publication",
        "quantity" => "quantité",
        "quantity_in_stock" => "quantité en stock",
        "quantity_to_order" => "quantité à commander",
        "quantity_to_order.*" => "d'une des quantités à commander",
        "quantities_to_order" => "d'une des quantités à commander",
        "quantities_to_order.*" => "d'une des quantités à commander",
        "quantity_to_order_sav" => "quantité à commander (SAV)",
        "quantity_to_order_sav.*" => "d'une des quantités à commander (SAV)",
        "quantities_to_order_sav" => "d'une des quantités à commander (SAV)",
        "quantities_to_order_sav.*" => "d'une des quantités à commander (SAV)",
        "quantity_to_remove_to_stock" => "quantité à enlever au stock",
        "quantity_to_remove_to_stock.*" => "d'une des quantités à enlever au stock",
        "quantities_to_remove_to_stock" => "quantité à enlever au stock",
        "quantities_to_remove_to_stock.*" => "d'une des quantités à enlever au stock",
        "quantities_to_remove_to_reserve_stock" => "quantité à enlever au stock de réserve",
        "quantities_to_remove_to_reserve_stock.*" => "d'une des quantités à enlever au stock de réserve",
        "quantity_to_remove_to_stock_sav" => "quantité à enlever au stock (SAV)",
        "quantity_to_remove_to_stock_sav.*" => "d'une des quantités à enlever au stock (SAV)",
        "quantities_to_remove_to_stock_sav" => "quantité à enlever au stock (SAV)",
        "quantities_to_remove_to_stock_sav.*" => "d'une des quantités à enlever au stock (SAV)",
        "quantities_to_remove_to_reserve_stock_sav" => "quantité à enlever au stock de réserve (SAV)",
        "quantities_to_remove_to_reserve_stock_sav.*" => "d'une des quantités à enlever au stock de réserve (SAV)",
        "rate" => "taux",
        "real_stock" => "stock réel",
        "reception_desired_for_the" => "réception souhaité pour le",
        "reception_planned_at" => "réception prévue le",
        "reference" => "référence",
        "response" => "réponse",
        "responses" => "réponses",
        "role" => "rôle",
        "row_number" => "nombre",
        "row_reference" => "référence",
        "second" => "seconde",
        "sex" => "sexe",
        "shop_id" => "magasin",
        "shops_id" => "magasins",
        "shops_id.*" => "d'un des magasins",
        "shop_id_active" => "magasin actif",
        "short_title" => "titre court",
        "siren" => "numéro de siren",
        "siret" => "numéro de siret",
        "size" => "taille",
        "status" => "statut",
        "subdirectory_where_create_directory" => "dans quel sous-dossier créer ce dossier",
        "subdirectory" => "sous-dossier",
        "subject" => "sujet",
        "subdirectory_where_upload" => "dans quel sous-dossier uploader le(s) fichier(s)",
        "summary" => "chapô",
        "supplier_id" => "fournisseur",
        "suppliers_to_order_id" => "fournisseur d'une marque",
        "suppliers_to_order_id.*" => "d'un des fournisseurs d'une marque",
        "suppliers_to_order_id_sav" => "fournisseur d'une marque (SAV)",
        "suppliers_to_order_id_sav.*" => "d'un des fournisseurs d'une marque (SAV)",
        "tax_id" => "TVA",
        "tel" => "téléphone",
        "time" => "heure",
        "title" => "titre",
        "to_ordered_the" => "à commander pour le",
        "username" => "pseudo",
        "user_id" => "utilisateur",
        "users_id" => "utilisateurs",
        "users_installers_id" => "poseurs",
        "users_installers_id.*" => "d'un des poseurs",
        "value" => "valeur",
        "website" => "site web",
        "year" => "année",
    ],

];
